export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_ERROR = "ORDER_CREATE_ERROR"

export const ORDER_RETRIEVE_REQUEST = "ORDER_RETRIEVE_REQUEST"
export const ORDER_RETRIEVE_SUCCESS = "ORDER_RETRIEVE_SUCCESS"
export const ORDER_RETRIEVE_ERROR = "ORDER_RETRIEVE_ERROR"
