export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_ERROR = "ORDER_CREATE_ERROR"

export const ORDER_RETRIEVE_REQUEST = "ORDER_RETRIEVE_REQUEST"
export const ORDER_RETRIEVE_SUCCESS = "ORDER_RETRIEVE_SUCCESS"
export const ORDER_RETRIEVE_ERROR = "ORDER_RETRIEVE_ERROR"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_ERROR = "ORDER_PAY_ERROR"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST"
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS"
export const GET_MY_ORDERS_ERROR = "GET_MY_ORDERS_ERROR"
export const GET_MY_ORDERS_RESET = "GET_MY_ORDERS_RESET"

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST"
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS"
export const GET_ALL_ORDERS_ERROR = "GET_ALL_ORDERS_ERROR"

export const DELIVER_ORDER_REQUEST = "DELIVER_ORDER_REQUEST"
export const DELIVER_ORDER_SUCCESS = "DELIVER_ORDER_SUCCESS"
export const DELIVER_ORDER_ERROR = "DELIVER_ORDER_ERROR"
export const DELIVER_ORDER_RESET = "DELIVER_ORDER_RESET"
