export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_ERROR = "ORDER_CREATE_ERROR"

export const ORDER_RETRIEVE_REQUEST = "ORDER_RETRIEVE_REQUEST"
export const ORDER_RETRIEVE_SUCCESS = "ORDER_RETRIEVE_SUCCESS"
export const ORDER_RETRIEVE_ERROR = "ORDER_RETRIEVE_ERROR"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_ERROR = "ORDER_PAY_ERROR"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"
