export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_ERROR = "PRODUCT_DETAILS_ERROR"

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST"
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR"

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST"
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS"
export const PRODUCT_CREATE_ERROR = "PRODUCT_CREATE_ERROR"

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST"
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS"
export const PRODUCT_UPDATE_ERROR = "PRODUCT_UPDATE_ERROR"

export const PRODUCT_REVIEW_REQUEST = "PRODUCT_REVIEW_REQUEST"
export const PRODUCT_REVIEW_SUCCESS = "PRODUCT_REVIEW_SUCCESS"
export const PRODUCT_REVIEW_ERROR = "PRODUCT_REVIEW_ERROR"
export const PRODUCT_REVIEW_RESET = "PRODUCT_REVIEW_RESET"

export const TOP_PRODUCTS_SUCCESS = "TOP_PRODUCTS_SUCCESS"
export const TOP_PRODUCTS_ERROR = "TOP_PRODUCTS_ERROR"
export const TOP_PRODUCTS_REQUEST = "TOP_PRODUCTS_REQUEST"

export const CLEAR_MSG = "CLEAR_MSG"
