export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_LOADED = "USER_LOGIN_LOADED"
export const USER_LOGIN_OUT = "USER_LOGIN_OUT"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_RESET = "USER_DETAILS_RESET"
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR"

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR"
export const USER_UPDATE_RESET = "USER_UPDATE_RESET"

export const USERS_LIST_REQUEST = "USERS_LIST_REQUEST"
export const USERS_LIST_SUCCESS = "USERS_LIST_SUCCESS"
export const USERS_LIST_ERROR = "USERS_LIST_ERROR"
